parameters:
#    mobilis_store.example.class: Mobilis\StoreBundle\Example

services:
#    mobilis_store.example:
#        class: %mobilis_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
