parameters:
#    mobilis_user.example.class: Mobilis\UserBundle\Example

services:
#    mobilis_user.example:
#        class: %mobilis_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
